env:
  prod

spring:
  # 数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.88.216.172:3306/safe-api?serverTimezone=Asia/Shanghai&useSSL=false&characterEncoding=utf8
    username: root
    password: cdfd2ws$RF0917




